<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

|Term | Description|
|---|---|
| Subsetting | Picking a subset from a list or array |
| Indexing | Picking one element |
| Slicing | Picking a range of elements |
| Masking | Picking a range of elements based on a predicate |

# Exercise 2

In [1]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

print(np_array_2d[np_array_2d[:, 0].astype(int) % 2 == 1][:, 1])

['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [5]:
np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

np_array[np_array < 50] = -1
np_array[np_array > 50] = 1
np_array[np_array == 50] = 0

print(np_array)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
